export { default as email } from './email';
export { default as url } from './url';
export { default as number } from './number';
export { default as min } from './min';
export { default as max } from './max';
export { default as minmax } from './min-max';
export { default as minlength } from './min-length';
export { default as maxlength } from './max-length';
export { default as minmaxlength } from './min-max-length';
